---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  deprecations_as_errors: true

platforms:
  - name: amazon-linux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: fedora-latest
  - name: opensuse-leap-15
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: windows-2012-r2
    driver_config:
      box: tas50/windows_2012r2
  - name: windows-2016
    driver_config:
      box: tas50/windows_2016

suites:
  - name: default
    run_list:
      - recipe[f5_test::test_create_pool]
      - recipe[f5_test::test_create_vip]
    attributes:
      fqdn: local.kitchen.node
      ipaddress: 127.0.0.1
      f5:
        credentials:
          default:
            username: <%= ENV['F5_USERNAME'] %>
            password: <%= ENV['F5_PASSWORD'] %>
            host: <%= ENV['F5_HOST'] %>
