name             'f5'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures f5'
long_description 'Installs/Configures f5'
version          '0.1.0'
